version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=assword
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB_NAME=ingredients_db

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: assword
      MONGO_INITDB_DATABASE: ingredients_db
    volumes:
      - mongo_data:/data/db

  ui:
    build:
      context: ./smart-fridge-app-ui
      dockerfile: Dockerfile
    ports:
      - "5173:80"

volumes:
  mongo_data:

networks:
  frontend:
    driver: bridge
